# Node.js
# Build a general Node.js application with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/javascript

name: Frontend Masters Boot Camp

pool:
  vmImage: "Ubuntu 16.04"

trigger:
  - master

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "8.x"
    displayName: "Installing Node.js"

  - script: |
      npm ci # Use Package lock to install CI stuff, faster, more sercure
      npm run build
    displayName: "Running npm install and build"

  - task: CopyFiles@2
    inputs:
      sourceFolder: "$(System.DefaultWorkingDirectory)/public"
      contents: |
        **/*
      targetFolder: "$(Build.ArtifactStagingDirectory)"
      overWrite: true
    displayName: "Copying built static files"

  - task: PublishBuildArtifacts@1
